### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by D-06** [Lost-MSth/Arcaea-server#37]
```
[2022-02-05 09:38:21,849] WARNING in init: File `database/arcaea_database.db` is missing.           

[2022-02-05 09:38:21,849] INFO in init: Try to new the file `database/arcaea_database.db`.          

[2022-02-05 09:38:21,970] INFO in init: Success to new the file `database/arcaea_database.db`.      

[2022-02-05 09:38:21,971] INFO in main: Start to initialize data in 'songfile' table...             

[2022-02-05 09:38:21,992] INFO in main: Complete! 

[2022-02-05 09:38:21,998] INFO in main: UDP server is running...                                     * Serving Flask app 'main' (lazy loading)         * Environment: production                           WARNING: This is a development server. Do not use it in a production deployment.                    Use a production WSGI server instead.           * Debug mode: off                                Traceback (most recent call last):                  File "/root/Arcaea-server/latest version/main.py", line 901, in <module>                              main()                                          File "/root/Arcaea-server/latest version/main.py", line 890, in main                                  app.run(Config.HOST, Config.PORT)               File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 920, in run                          run_simple(t.cast(str, host), port, self, **options)                                              File "/usr/local/lib/python3.9/dist-packages/werkzeug/serving.py", line 1010, in run_simple           inner()                                         File "/usr/local/lib/python3.9/dist-packages/werkzeug/serving.py", line 950, in inner                 srv = make_server(                              File "/usr/local/lib/python3.9/dist-packages/werkzeug/serving.py", line 782, in make_server           return ThreadedWSGIServer(                      File "/usr/local/lib/python3.9/dist-packages/werkzeug/serving.py", line 688, in __init__              super().__init__(server_address, handler)  # type: ignore                                         File "/usr/lib/python3.9/socketserver.py", line 452, in __init__                                      self.server_bind()                              File "/usr/lib/python3.9/http/server.py", line 138, in server_bind                                    socketserver.TCPServer.server_bind(self)        File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind                                   self.socket.bind(self.server_address)         PermissionError: [Errno 13] Permission denied

```

**Comment by Lost-MSth** [comment]
I guess it is a port conflict problem. Please check the port you used or try another port.

**Comment by D-06** [comment]
Thanks it works by the way i wonder how can i patch the game to point to my ip address

**Comment by Lost-MSth** [comment]
Many ways. It depends on your ability and your expectation.

You can look at the discussions and old issues to know more (by translation).
Or you can try it by yourself.

A tip is the requirements I gave in the README.
