### ISSUE TITLE
Termux 中开启 UDP 服务端导致崩溃

### ISSUE THREAD

**Issue by Young-Lord** [Lost-MSth/Arcaea-server#48]
Arcaea-server 为最新版，此问题并未出现在最近3个 commit 前
```
~ $ python /storage/emulated/0/Download/Arcaea-server/main.py
[2022-04-15 23:08:39,618] INFO in main: Start to initialize data in 'songfile' table...
[2022-04-15 23:08:39,631] INFO in main: Complete!
Traceback (most recent call last):
  File "/storage/emulated/0/Download/Arcaea-server/main.py", line 903, in <module>
    main()
  File "/storage/emulated/0/Download/Arcaea-server/main.py", line 885, in main
    [p.start() for p in process]
  File "/storage/emulated/0/Download/Arcaea-server/main.py", line 885, in <listcomp>
    [p.start() for p in process]
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 39, in _launch
    from . import resource_tracker
  File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/resource_tracker.py", line 38, in <module>
    import _posixshmem
ModuleNotFoundError: No module named '_posixshmem'
~ $ python --version                                       Python 3.10.2
~ $ uname -a
Linux localhost 3.18.124-g24821698656f #1 SMP PREEMPT Tue Sep 21 04:44:10 CST 2021 aarch64 Android
```

**Comment by Young-Lord** [comment]
我不确定是不是 Termux 的问题……所以先close掉了

**Comment by Lost-MSth** [comment]
这不是multiprocessing标准库报错吗，应该去向python提issue（不是）
并不清楚这个问题怎么解决（

**Comment by Young-Lord** [comment]
看起来确实是 Termux 的问题，哪怕是最简单的多进程，只要用 `spawn` 模式都会报错
