### ISSUE TITLE
在linux运行时出现的错误

### ISSUE THREAD

**Issue by ialdaiaxiariyay** [Lost-MSth/Arcaea-server#77]
在运行main. py时出现了下面的错误
(tutorial-env) [root@localhost v2.10.1]# python -B main.py
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    import api
  File "/opt/ffg/v2.10.1/api/__init__.py", line 3, in <module>
    from . import users
  File "/opt/ffg/v2.10.1/api/users.py", line 2, in <module>
    from core.score import Potential, UserScoreList
  File "/opt/ffg/v2.10.1/core/score.py", line 10, in <module>
    from .sql import Query, Sql
  File "/opt/ffg/v2.10.1/core/sql.py", line 1, in <module>
    import sqlite3
  File "/usr/local/lib/python3.8/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.8/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
尝试安装这个库
(tutorial-env) [root@localhost v2.10.1]# pip install sqlite3
Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple
ERROR: Could not find a version that satisfies the requirement sqlite3 (from versions: none)
ERROR: No matching distribution found for sqlite3
不存在，所以我不知道怎么办了

**Comment by Lost-MSth** [comment]
sqlite3是内置库，显然不能用pip装，可能很麻烦，怎么应对此情况您应该先去问问搜索引擎，错误信息直接复制就能得到答案

**Comment by ialdaiaxiariyay** [comment]
我已经解决了，谢谢
